// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr8gbSmc9qLaR4xtv9XBC2nDWW3O3APMM',
    appId: '1:143162387248:android:7952afe425f74a826db6f5',
    messagingSenderId: '143162387248',
    projectId: 'logic-loomer-fb-login',
    storageBucket: 'logic-loomer-fb-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30H0RiFp36h5IjlKDhI3KzOVnaMLooC8',
    appId: '1:143162387248:ios:29e750a191e091406db6f5',
    messagingSenderId: '143162387248',
    projectId: 'logic-loomer-fb-login',
    storageBucket: 'logic-loomer-fb-login.appspot.com',
    iosBundleId: 'com.example.internshipTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAns1_BI0yUP2s_yNzaNL424AAUz3I6zZM',
    appId: '1:143162387248:web:0fed0dedddc2aaa56db6f5',
    messagingSenderId: '143162387248',
    projectId: 'logic-loomer-fb-login',
    authDomain: 'logic-loomer-fb-login.firebaseapp.com',
    storageBucket: 'logic-loomer-fb-login.appspot.com',
  );
}
